config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'policy', to: 'static_pages#policy'
  post 'callback', to: 'line_bots#callback'
  resources :videos, only: %i[index show] do
    get 'bookmarks', on: :collection
  end
  resources :users, only: %i[new create]
  resources :watches, only: %i[create destroy]
  resources :bookmarks, only: %i[create destroy]
  resources :actives, only: %i[index new create destroy]

  namespace :admin do
    resources :users, only: %i[new create]
    resources :videos
    resources :actives, only: %i[index destroy]
  end
end

app/models/active.rb
class Active < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :visited_on
    validates :sauna_minute
    validates :water_bath_minute
    validates :break_minute
    validates :cycle_count
    validates :score
  end

  def self.chart_order
    distinct.order(visited_on: :asc).pluck(:visited_on, :score)
  end
end

app/controllers/actives_controller.rb
class ActivesController < ApplicationController
  before_action :set_search
  before_action :set_liff_id, only: %i[index]

  def index
    @views = WatchDecorator.decorate(Watch.total(current_user.id))
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    actives = current_user.actives.where(visited_on: @month.all_month)
    @actives_chart = actives.chart_order
    @actives = actives.order(visited_on: :desc).page(params[:page])
  end

  def new
    @active = Active.new
  end

  def create
    @active = current_user.actives.build(active_params)
    if @active.valid?
      sauna_score if @active.sauna_minute >= 6
      water_bath_score if @active.water_bath_minute >= 1
      cycle_score if @active.cycle_count >= 2
    end
    if @active.save
      redirect_to actives_path, success: "サ活を記録しました。ととのい度「#{@active.score}」です。"
    else
      flash.now[:danger] = 'サ活を記録できませんでした'
      render :new
    end
  end

  def destroy
    @active = Active.find(params[:id])
    @active.destroy!
    redirect_to actives_path, success: 'サ活の記録を削除しました'
  end

  private

  def active_params
    params.require(:active).permit(:visited_on, :sauna_minute, :water_bath_minute,
                                   :break_minute, :cycle_count).merge(score: 60)
  end

  def sauna_score
    @active.score = case @active.sauna_minute
                    when 6..8
                      @active.score + 4
                    when 9..11
                      @active.score + 8
                    else
                      @active.score + 10
                    end
  end

  def water_bath_score
    @active.score = case @active.water_bath_minute
                    when 1
                      @active.score + 7
                    else
                      @active.score + 10
                    end
  end

  def cycle_score
    @active.score = case @active.cycle_count
                    when 2
                      @active.score + 10
                    else
                      @active.score + 20
                    end
  end
end

app/controllers/admin/actives_controller.rb
class Admin::ActivesController < Admin::BaseController
  before_action :authorize_active

  def index
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    @actives = Active.where(visited_on: @month.all_month).order(visited_on: :desc).page(params[:page])
  end

  def destroy
    @active = Active.find(params[:id])
    @active.destroy!
    redirect_to admin_actives_path, success: 'サ活の記録を削除しました'
  end

  private

  def authorize_active
    authorize(Active)
  end
end

app/views/actives/_active.html.slim
.row
  .col-4.offset-1
    p.mb-1.fw-light #{active.visited_on}
  .col-1.offset-5
    = link_to active_path(active), method: :delete, data: { confirm: '本当に削除してもよろしいでしょうか？' } do
      i.fa-solid.fa-trash-can
  h6.mb-1 サウナ：#{active.sauna_minute}分 × #{active.cycle_count}回
  h6.mb-1 水風呂：#{active.water_bath_minute}分 × #{active.cycle_count}回
  h6.mb-3 外気浴：#{active.break_minute}分 × #{active.cycle_count}回
  h6.mb-2 ととのい度：#{active.score}
  .border-bottom

app/views/actives/_form.html.slim
= form_with model: active, local: true do |f|
  = render 'shared/error_message', object: f.object
  .col-8.offset-2
    .form-group
      = f.label :visited_on, '訪問日'
      = f.date_field :visited_on, value: Date.today.strftime("%Y-%m-%d"), class: 'form-control'
    .form-group
      = f.label :sauna_minute, 'サウナの入浴時間（分）'
      = f.number_field :sauna_minute, class: 'form-control', placeholder: '例：10'
    .form-group
      = f.label :water_bath_minute, '水風呂の入浴時間（分）'
      = f.number_field :water_bath_minute, class: 'form-control', placeholder: '例：1'
    .form-group
      = f.label :break_minute, '外気浴の入浴時間（分）'
      = f.number_field :break_minute, class: 'form-control', placeholder: '例：10'
    .form-group
      = f.label :cycle_count, '合計セット回数'
      = f.number_field :cycle_count, class: 'form-control', placeholder: '例：10'
    .text-center
      = f.submit '記録する', class:'btn btn-blue mt-3'
    .text-center.my-5
      = link_to 'キャンセル', actives_path, data: { 'turbolinks': false }, class: 'link-dark text-decoration-none'

app/views/actives/index.html.slim
= javascript_pack_tag 'actives/index'
.container
  .text-center.my-4
    = image_pack_tag 'icon.png', id: 'picture', class: 'rounded-circle border border-3 icon'
    h6#name.mt-2.mb-3
    = render 'shared/send_message'
    h6
      i.fa-solid.fa-circle-check.fa-lg
      | &nbsp;動画視聴状況：#{@views.percent}%
    .progress.mx-4.mb-5.border.border-2
      .progress-bar role="progressbar" style="width: #{@views.percent}%;" aria-valuenow="#{@views.percent}" aria-valuemin="0" aria-valuemax="100"

    .row
      .col-2
        = link_to actives_path(month: @month.prev_month), data: { 'turbolinks': false } do
          i.fa-solid.fa-circle-chevron-left.fa-2x
      .col-8.px-0
        h5 #{@month.year}年#{@month.month}月のサ活レポート
      .col-2
        = link_to actives_path(month: @month.next_month), data: { 'turbolinks': false } do
          i.fa-solid.fa-circle-chevron-right.fa-2x
    h6.mt-3 ととのい度グラフ
    = column_chart @actives_chart, height: '200px', colors: ['#00B900', '#5DE15D']
    = link_to new_active_path, class: 'btn btn-blue btn-lg fixed-btn' do
      i.fa-solid.fa-pencil
      | &nbsp;&nbsp;記録
    h6.mt-4 記録一覧
    - if @actives.present?
      #active-pagenate
        = render @actives
    - else
      h6.fw-light.text-center.mt-3
        | #{@month.month}月の記録はありませんでした。
    .d-grid.mt-3.mb-5
      = link_to_next_page @actives, 'もっと見る', remote: true, class: 'btn btn-light border border-2', id: 'more-link'

app/views/actives/index.js.slim
| $('#active-pagenate').append('#{render @actives}');
| $('#more-link').replaceWith("#{j(link_to_next_page(@actives, 'もっと見る', remote: true, class: 'btn btn-light border border-2', id: 'more-link'))}")

app/views/actives/new.html.slim
.container
  .row.justify-content-center.mt-3
    .col-lg-6
      h2 サ活記録
      = render 'form', active: @active

app/views/actives/show.html.slim
= javascript_pack_tag 'actives/show'
- if current_user
  = render 'shared/header'
.container
  .text-center.my-5
    = image_pack_tag 'icon.png', id: 'picture', class: 'rounded-circle border border-3 icon'
    h5#name.mt-2.mb-5
    h6
      i.fa-solid.fa-circle-check.fa-lg
      | &nbsp;動画視聴状況：#{@views.percent}%
    .progress.mx-4.border.border-2
      .progress-bar role="progressbar" style="width: #{@views.percent}%;" aria-valuenow="#{@views.percent}" aria-valuemin="0" aria-valuemax="100"
    = render 'shared/send_message'

    h5 #{@month.year}年#{@month.month}月のサ活レポート
    = link_to "前の月のリンク", actives_path(month: @month.prev_month)
    = link_to "次の月のリンク", actives_path(month: @month.next_month)
    = column_chart @actives_chart
    = link_to 'サ活作成', new_actives_path, class: 'btn btn-info mt-3'
    br
    - @actives.each do |active|
      = active.visited_on
      br
      = active.sauna_minute
      br
      = active.water_bath_minute
      br
      = active.break_minute
      br
      = active.cycle_count
      br
      = active.score
      br