config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'policy', to: 'static_pages#policy'
  post 'callback', to: 'line_bots#callback'
  resources :videos, only: %i[index show] do
    get 'bookmarks', on: :collection
  end
  resources :users, only: %i[new create]
  resources :watches, only: %i[create destroy]
  resources :bookmarks, only: %i[create destroy]
  resources :actives, only: %i[index new create destroy]

  namespace :admin do
    resources :users, only: %i[new create]
    resources :videos
    resources :actives, only: %i[index destroy]
  end
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :watches, dependent: :destroy
  has_many :watch_users, through: :watches, source: :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user

  with_options presence: true do
    validates :youtube_id
    validates :address
    validates :sauna
  end

  validates :youtube_id, uniqueness: true
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  before_action :set_video, only: %i[show edit update destroy]
  before_action :authorize_video

  def index
    @q = Video.ransack(params[:q])
    @videos = @q.result(distinct: true).page(params[:page])
  end

  def show
    gon.video = @video
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to admin_videos_path, success: '動画を追加しました'
    else
      flash.now[:danger] = '動画を追加できませんでした'
      render :new
    end
  end

  def edit; end

  def update
    if @video.update(video_params)
      redirect_to admin_video_path(@video), success: '動画を更新しました'
    else
      flash.now[:danger] = '動画を更新できませんでした'
      render :edit
    end
  end

  def destroy
    @video.destroy!
    redirect_to admin_videos_path
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:youtube_id, :address, :sauna)
  end

  def authorize_video
    authorize(Video)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :login_required
  before_action :set_search, only: %i[index show]
  before_action :set_liff_id, only: %i[show]
  before_action :current_user

  def index; end

  def show
    @video = Video.find(params[:id])
    gon.video = @video
    # Youtube動画情報を取得
    @youtube = OembedInterface.new(@video).response
  end

  def bookmarks
    @q = current_user.bookmark_videos.ransack(params[:q])
    @bookmark_videos = @q.result(distinct: true).page(params[:page])
  end
end

app/views/videos/_bookmark.html.slim
div id="js-bookmark-button-for-video-#{video.id}"
  = link_to bookmarks_path(video_id: video.id), method: :post, remote: true do
    i.fa-regular.fa-heart.fa-lg

app/views/videos/_unbookmark.html.slim
div id="js-bookmark-button-for-video-#{video.id}"
  = link_to bookmark_path(@current_user.bookmarks.find_by(video_id: video.id)), method: :delete, remote: true do
    i.fa-solid.fa-heart.fa-lg

app/views/videos/_unwatch.html.slim
= link_to watch_path(@current_user.watches.find_by(video_id: video.id)), id: "js-watch-button-for-video-#{video.id}", role: 'button', method: :delete, remote: true do
  h5
    span.badge.bg-light.text-dark
      i.fa-solid.fa-circle-check.fa-lg
      | &nbsp;視聴済

app/views/videos/_video.html.slim
.row.mt-3
  .col-6.px-2
    = image_tag "https://img.youtube.com/vi/#{video.youtube_id}/mqdefault.jpg", class: 'img-fluid rounded'
  .col-6.px-2
    = link_to video, data: { 'turbolinks': false } do
      p.mb-0.link-dark.fw-bolder.text-truncate #{video.sauna}
    p.mb-1.fw-light.text-truncate #{video.address}
    - if current_user
      .row.mt-3
        .col-7
          - if current_user.bookmark?(video)
            = render 'unbookmark', { video: video }
          - else
            = render 'bookmark', { video: video }
        .col-5
          - if current_user.watched?(video)
            i.fa-solid.fa-circle-check.fa-lg

app/views/videos/_watch.html.slim
= link_to watches_path(video_id: video.id), id: "js-watch-button-for-video-#{video.id}", role: 'button', method: :post, remote: true do
  h5
    span.badge.bg-light.text-dark
      | 視聴済にする

app/views/videos/bookmarks.html.slim
.container
  .row.justify-content-center.mt-3
    .col-lg-6
      h2 お気に入り動画
      - if @bookmark_videos.present?
        #video-pagenate
          = render @bookmark_videos
      - else
        h6.fw-light.text-center.mt-3
          | 該当するサウナ動画は見つかりませんでした。
      .d-grid.mt-3.mb-5
        = link_to_next_page @bookmark_videos, 'もっと見る', remote: true, class: 'btn btn-light border border-2', id: 'more-link'

app/views/videos/bookmarks.js.slim
| $('#video-pagenate').append('#{render @bookmark_videos}');
| $('#more-link').replaceWith("#{j(link_to_next_page(@bookmark_videos, 'もっと見る', remote: true, class: 'btn btn-light border border-2', id: 'more-link'))}")

app/views/videos/index.html.slim
.container
  .row.justify-content-center.mt-3
    .col-lg-6
      h2 動画一覧
      - if @videos.present?
        #video-pagenate
          = render @videos
      - else
        h6.fw-light.text-center.mt-3
          | 該当するサウナ動画は見つかりませんでした。
      .d-grid.mt-3.mb-5
        = link_to_next_page @videos, 'もっと見る', remote: true, class: 'btn btn-light border border-2', id: 'more-link'

app/views/videos/show.html.slim
= javascript_pack_tag 'videos/show'
.container
  .row.justify-content-center.mt-3
    .col-lg-8
      h2.mb-2 #{@video.sauna}
      p.my-0.fw-light #{@video.address}
      .ratio.ratio-16x9
        / 以下の#playerはyoutubeのiframeに入れ替わる。
        #player
      h5.my-2
        = title(@youtube)
      hr.my-1
      .row
        .col-10.px-3
          p.mb-0
            = author_name(@youtube)
        .col-2
          = link_to "https://twitter.com/share?url=#{request.url}/&text=#{@video.sauna} - サウナイコ&hashtags=サウナイコ,サウナ", target: '_blank', rel: 'noopener noreferrer' do
            i.fa-brands.fa-twitter.fa-lg style='color: #3399FF;'
      - if current_user
        .row.justify-content-center.mt-2
          .col-3
            - if current_user.bookmark?(@video)
              = render 'unbookmark', { video: @video }
            - else
              = render 'bookmark', { video: @video }
          .col-3
            - if current_user.watched?(@video)
              = render 'unwatch', { video: @video }
            - else
              = render 'watch', { video: @video }
    = link_to "https://www.google.com/maps/search/?api=1&query=#{@video.sauna}&query_place_id=#{@video.address}", target: :_blank, rel: "noopener noreferrer", class: "col-7 mt-4 btn btn-blue" do
      p.my-0
        i.fa-solid.fa-up-right-from-square
        | &nbsp;&nbsp;Googleマップをみる
    - if current_user
      = render 'shared/send_message'
    - else
      = render 'shared/line_promotion'