config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'policy', to: 'static_pages#policy'
  post 'callback', to: 'line_bots#callback'
  resources :videos, only: %i[index show] do
    get 'bookmarks', on: :collection
  end
  resources :users, only: %i[new create]
  resources :watches, only: %i[create destroy]
  resources :bookmarks, only: %i[create destroy]
  resources :actives, only: %i[index new create destroy]

  namespace :admin do
    resources :users, only: %i[new create]
    resources :videos
    resources :actives, only: %i[index destroy]
  end
end

app/views/shared/_before_login_header.html.slim
header
  nav.bg-gray.py-2
    .container-fluid
      .row.align-items-center
        = link_to root_path, class: "col-auto mx-2 p-0" do
          = image_pack_tag 'logo.png', class: "logo-size"
        .col-7.offset-md-2.px-0
          = render 'shared/search_form', url: videos_path

app/views/shared/_bookmark_header.html.slim
header
  nav.navbar.navbar-expand-lg.navbar-light.bg-gray.py-2
    .container
      .row.align-items-center
        = render 'shared/search_form', url: bookmarks_videos_path
      - if current_user
        = render 'shared/drawer'

app/views/shared/_drawer.html.slim
button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"
  span.navbar-toggler-icon
.collapse.navbar-collapse#navbarNav
  ul.navbar-nav.text-end
    li.nav-item.mt-4
      = link_to actives_path, class: 'nav-link py-0', data: { 'turbolinks': false } do
        h6
          i.fa-solid.fa-circle-user.fa-lg
          | &nbsp;&nbsp;サ活
    li.nav-item.mt-4
      = link_to videos_path, class: 'nav-link py-0' do
        h6
          i.fa-solid.fa-circle-play.fa-lg
          | &nbsp;&nbsp;動画一覧
    li.nav-item.mt-4
      = link_to bookmarks_videos_path, class: 'nav-link py-0' do
        h6
          i.fa-solid.fa-hand-holding-heart.fa-lg
          | &nbsp;&nbsp;お気に入り動画

app/views/shared/_error_message.html.slim
- if object.errors.any?
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |message|
        li
          = message

app/views/shared/_flash_message.html.slim
- flash.each do |message_type, message|
  div class="alert alert-#{message_type}"
    = message

app/views/shared/_footer.html.slim
footer.footer.bg-gray.border-top style="height:140px;"
  .container-fluid
    .row.justify-content-around
      .col-sm-4.text-center.mt-2
        = link_to '利用規約', terms_path, class: "text-decoration-none text-muted"
      .col-sm-4.text-center.mt-2
        = link_to 'プライバシーポリシー', policy_path, class: "text-decoration-none text-muted"
      .col-sm-4.text-center.mt-2
        = link_to 'お問い合わせ', "https://forms.gle/LYM7aMbz7jVQ5rRh7", class: "text-decoration-none text-muted", target: :_blank, rel: "noopener noreferrer"
    .text-center.mt-2
      p.text-muted © 2022 サウナイコ

app/views/shared/_header.html.slim
header
  nav.navbar.navbar-expand-lg.navbar-light.bg-gray.py-2
    .container
      .row.align-items-center
        = render 'shared/search_form', url: videos_path
      - if current_user
        = render 'shared/drawer'

app/views/shared/_line_promotion.html.slim
.text-center
  h4.mt-4 LINEアカウントはじめました！
  .my-3
    = link_to 'https://lin.ee/if0kUVq' do
      = image_tag 'https://scdn.line-apps.com/n/line_add_friends/btn/ja.png', alt: '友だち追加', height: '36', border: '0'
  .row.justify-content-around
    .col-md-3.my-4
      h5 1.&nbsp;楽しみ方を学べる
      p チャット形式でサウナの入り方と、ととのうコツを学べます。
      = image_pack_tag 'add_friend_1.png', class: "img-size"
    .col-md-3.my-4
      h5 2.&nbsp;友だちを誘える
      p 友だちにサウナのお誘いと楽しみ方を伝えることができます。
      = image_pack_tag 'add_friend_2.png', class: "img-size"
    .col-md-3.my-4
      h5 3.&nbsp;サ活を管理できる
      p 入浴時間とセット数を記録すると「ととのい度」がわかります。
      = image_pack_tag 'add_friend_3.png', class: "img-size"

app/views/shared/_send_message.html.slim
.text-center.mt-4.mb-5
  button#send-message.btn.btn-lg.offset-1.mx-2
    i.fa-solid.fa-paper-plane
    | &nbsp;&nbsp;友だちを誘ってみる
  button#modal.btn.btn-blue.btn-sm data-bs-target="#exampleModal" data-bs-toggle="modal" type="button"
    | ？
  #exampleModal.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" tabindex="-1"
    .modal-dialog
      .modal-content
        .modal-header
          h5#exampleModalLabel.modal-title 友だちに送信するメッセージ内容
          button.btn-close aria-label="Close" data-bs-dismiss="modal" type="button"
        .modal-body
          = image_pack_tag 'add_friend_2.png', class: "img-size"