config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'policy', to: 'static_pages#policy'
  post 'callback', to: 'line_bots#callback'
  resources :videos, only: %i[index show] do
    get 'bookmarks', on: :collection
  end
  resources :users, only: %i[new create]
  resources :watches, only: %i[create destroy]
  resources :bookmarks, only: %i[create destroy]
  resources :actives, only: %i[index new create destroy]

  namespace :admin do
    resources :users, only: %i[new create]
    resources :videos
    resources :actives, only: %i[index destroy]
  end
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :watches, dependent: :destroy
  has_many :watch_users, through: :watches, source: :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user

  with_options presence: true do
    validates :youtube_id
    validates :address
    validates :sauna
  end

  validates :youtube_id, uniqueness: true
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  before_action :set_video, only: %i[show edit update destroy]
  before_action :authorize_video

  def index
    @q = Video.ransack(params[:q])
    @videos = @q.result(distinct: true).page(params[:page])
  end

  def show
    gon.video = @video
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to admin_videos_path, success: '動画を追加しました'
    else
      flash.now[:danger] = '動画を追加できませんでした'
      render :new
    end
  end

  def edit; end

  def update
    if @video.update(video_params)
      redirect_to admin_video_path(@video), success: '動画を更新しました'
    else
      flash.now[:danger] = '動画を更新できませんでした'
      render :edit
    end
  end

  def destroy
    @video.destroy!
    redirect_to admin_videos_path
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:youtube_id, :address, :sauna)
  end

  def authorize_video
    authorize(Video)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :login_required
  before_action :set_search, only: %i[index show]
  before_action :set_liff_id, only: %i[show]
  before_action :current_user

  def index; end

  def show
    @video = Video.find(params[:id])
    gon.video = @video
    # Youtube動画情報を取得
    @youtube = OembedInterface.new(@video).response
  end

  def bookmarks
    @q = current_user.bookmark_videos.ransack(params[:q])
    @bookmark_videos = @q.result(distinct: true).page(params[:page])
  end
end

app/views/admin/videos/_form.html.slim
= form_with model: [:admin, video], local: true do |f|
  = render 'shared/error_message', object: f.object
  .form-group
    = f.label :youtube_id, 'YouTubeのID(11桁)'
    = f.text_field :youtube_id, class: 'form-control'
  .form-group
    = f.label :address, '住所'
    = f.text_field :address, class: 'form-control'
  .form-group
    = f.label :sauna, 'サウナ名'
    = f.text_field :sauna, class: 'form-control'
  = f.submit class:'btn btn-primary mt-3'
= link_to '動画一覧', admin_videos_path, class: 'btn btn-info mt-3'

app/views/admin/videos/_search_form.html.slim
= search_form_for @q, url: url do |f|
  .input-group
    = f.search_field :sauna_or_address_cont, class: "form-control search-form", placeholder: '地名か施設名を入力'
    .input-group-append
      = f.button :type => "submit", class: "btn btn-dark search-btn" do
        i.fa-solid.fa-magnifying-glass

app/views/admin/videos/_video.html.slim
.row.mt-3
  .col-6.px-2
    = image_tag "https://img.youtube.com/vi/#{video.youtube_id}/mqdefault.jpg", class: 'img-fluid rounded'
  .col-6.px-2
    = link_to admin_video_path(video), data: { 'turbolinks': false } do
      p.mb-0.link-dark.fw-bolder.text-truncate #{video.sauna}
    p.mb-1.fw-light.text-truncate #{video.address}
    .row.mt-3
      .col-6
        = link_to '編集', edit_admin_video_path(video), class: 'btn btn-success'
      .col-6
        = link_to '削除', admin_video_path(video), method: :delete, data: { confirm: '本当に削除してもよろしいでしょうか？' }, class: 'btn btn-danger'

app/views/admin/videos/edit.html.slim
.container
  .row.justify-content-center.mt-3
    .col-lg-6
      h2 動画編集
      = render 'form', video: @video

app/views/admin/videos/index.html.slim
.container
  .row.justify-content-center.mt-3
    .col-lg-6
      .row.my-2
        .col-8
          h2 動画一覧
        .col-4
          = link_to '動画追加', new_admin_video_path, class: 'btn btn-primary'
      = render 'shared/search_form', url: admin_videos_path
      - if @videos.present?
        #video-pagenate
          = render @videos
      .d-grid.mt-3.mb-5
        = link_to_next_page @videos, 'もっと見る', remote: true, class: 'btn btn-light border border-2', id: 'more-link'

app/views/admin/videos/index.js.slim
| $('#video-pagenate').append('#{render @videos}');
| $('#more-link').replaceWith("#{j(link_to_next_page(@videos, 'もっと見る', remote: true, class: 'btn btn-light border border-2', id: 'more-link'))}")

app/views/admin/videos/new.html.slim
.container
  .row.justify-content-center.mt-3
    .col-lg-6
      h2 動画追加
      = render 'form', video: @video

app/views/admin/videos/show.html.slim
= javascript_pack_tag 'admin/videos/show'
.container
  .row.justify-content-center.mt-3
    .col-lg-8
      = link_to '動画一覧', admin_videos_path, class: 'btn btn-info mt-3'
      h2.mb-2 #{@video.sauna}
      p.my-0.fw-light #{@video.address}
      .ratio.ratio-16x9
        / 以下の#playerはyoutubeのiframeに入れ替わる。
        #player
  .row.mt-3
    .col-6
      = link_to '編集', edit_admin_video_path(@video), class: 'btn btn-success'
    .col-6
      = link_to '削除', admin_video_path(@video), method: :delete, data: { confirm: '本当に削除してもよろしいでしょうか？' }, class: 'btn btn-danger'